contries = ['Japan','Costa Rica','Columbia','Canada','Greece']
print(contries)

newlis = sorted(contries)
print(newlis)
print(contries)
print(contries)
newlis = sorted(contries, reverse = True)
print(newlis)
print(contries)
newlis = contries.reverse()
print(newlis)
print(contries)
newlis = contries.reverse()
print(newlis)
print(contries)
